# Generated by Django 3.2.5 on 2021-07-20 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date_time',
            field=models.DateField(default=datetime.datetime(2021, 7, 20, 7, 9, 14, 74012, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.TimeField(default=datetime.datetime(2021, 7, 20, 7, 9, 14, 73016, tzinfo=utc)),
        ),
    ]
